data_root_path = '/media/hwejin/SSD_1/DATA/landmark/landmark_split'
data_root_path = '/media/hwejin/SSD_1/DATA/landmark/'
snapshot_root_path = '/media/hwejin/SSD_1/DATA/landmark/checkpoint'
#data_root_path = '../../landmark_data/landmark_split'
#snapshot_root_path = '../../landmark_data/checkpoints'
#train_val_set_dir = '../../landmark_data/csv'